### PR TITLE
Add iconHtml mount

### LINKED ISSUE #146: Add `iconHtml` as a react element
Hi!

It would be great if this library would also support `iconHtml` as a react element. We have a bunch of react element icons in our project and would be amazing if those can be re-used instead of rewriting them all into a css version.

I forked this project and tried adding this functionality but I'd appreciate some guidance. Here is the commit: https://github.com/mihaerzen/sweetalert2-react-content/commit/7bdd3efa28db6dd1ee1c02cc95f39c36225554c1

Specifically `swal.getIcon()` returns null and it could be the sweetalert library doesn't support this out of the box.

Any ideas?
Thank you very much!

### PR DESCRIPTION
**Pull request by limonte**
Closes #146

### CODE REVIEW

**Comment by limonte** [comment]
@zenflow would you mind helping me out with this PR? It seems to work when I test it with `test-build.html`, but in the CI build there are 2 issues:

1. Warning: Each child in a list should have a unique "key" prop.
2. Error: Uncaught [TypeError: Cannot read property 'innerHTML' of null]

Any help would be welcome, thanks!

**Comment by limonte** [comment]
@mihaerzen please take a look as well, you might also be able to help with the issues, thanks!

**Comment by mihaerzen** [comment]
Amazing, thanks!

**Review by zenflow — APPROVED** [review]
Can't find any issues! lgtm

**Pull request merged**
