### PR TITLE
Use didOpen and didDestroy instead of deprecated onOpen and onDestroy

### LINKED ISSUE #125: Use didOpen and didDestroy instead of deprecated onOpen and onDestroy
See https://github.com/sweetalert2/sweetalert2/pull/2057

`onOpen` and `onDestroy` were deprecated, use `didOpen` and `didDestroy` instead.

### PR DESCRIPTION
**Pull request by limonte**
Closes #125

### CODE REVIEW

**Review by zenflow — CHANGES_REQUESTED** [review]
This will be totally broken with sweetalert2 version < 10.3.0

**Comment by limonte** [comment]
> 
> 
> This will be totally broken with sweetalert2 version < 10.3.0

Right, should we release the new major with peerDependency `"sweetalert2": "^10.3.0"`? Or do you maybe know how it coulb be possible to use hooks without breaking things for `"sweetalert2": "<10.3.0"` users?

**Comment by zenflow** [comment]
> should we release the new major with peerDependency "sweetalert2": "^10.3.0"? 

I don't like the idea of making a breaking change to deal with the hook name changes which supposed to be (and are themselves) backwards-compatible

> Or do you maybe know how it could be possible to use new hooks without breaking things for "sweetalert2": "< 10.3.0" users?

Definitely possible.. I'm just not sure of the best way to go about it.

We could decide dynamically which hook names (original or updated) to use:
1. If we receive options with updated hook names, use updated hook names (This takes 1st priority since "Old hooks are still called if defined, **but only if the new name is not used simultaneously**,")
2. If we receive options with original hook names, use original hook names
3. If we receive options with no hooks, use hook names according to `Swal.version` (use updated hook names where possible and otherwise use original hook names).

There are some tricky edge cases there though, like what if we get a mix? (e.g. `onOpen` and `didDestroy`)
That wouldn't happen often, but could, especially if user has separated concerns by writing (or just using) custom enhancers.
I guess we evaluate which hook name to use on an individual basis? (i.e. determine which hook name to use for opening and separately determine which hook name to use for destroying)

**Comment by limonte** [comment]
@zenflow should be good to go now, please review 🚀

**Comment by limonte** [comment]
I also added `test-build-v9.html` so we can easily and quickly test against the previous major.

**Comment by limonte** [comment]
@zenflow I'll go ahead and merge this PR. Please review when you have time, thank you!

**Pull request merged**
