### PR TITLE
Add official keyword to README

### PR DESCRIPTION
**Pull request by limonte**
Because there's a ton of wrappers out there, let's label this one as "official".

PS. https://sweetalert2.github.io/#frameworks-integrations :tada:

### CODE REVIEW

**Comment by toverux** [comment]
Also @zenflow, you're saying that _"sweetalert2-react-content is a sweetalert2 decorator adding support for React elements as content."_
The word decorator is not wrong per-se but it's a bit misleading. I can only think about ES `@decorator`s. There's also the decorator pattern in OOP. Do we have a better word for this? Wrapper is technically good too but is too often associated with low-quality wrappers around sweetalert2's API. Maybe simply "integration"? Or am I the only one that have a problem with "decorator" ? 😄

**Comment by limonte** [comment]
> The word decorator is not wrong per-se but it's a bit misleading. I can only think about ES @decorators. There's also the decorator pattern in OOP. 

Same feeling here. "Integration" sounds better and "deeper".

**Comment by zenflow** [comment]
I want to describe what it (the default export) actually is here.. 

"integration" is not very specific here as to *how it integrates* or *what kind of integration*

"wrapper" does not seem to imply that the end product (wrapped thing) has a backwards compatible API .. and that more [wrappers/decorators] can be applied .. to the contrary, it seems to often be used to describe an "adapter"

"decorator" in the sense of the general pattern seems to be the most accurate and descriptive so far.. If we keep it we should probably be more explicit that we don't mean an ecmascript `@decorator`.

What about "mixin"? This word has an even more varied usage, but seems to describe pretty well how it works. 

Now that I think of it, whatever word it is, I think I'd like it in the name of the package, e.g. `@sweetalert2/mixin-react` or `sweetalert2-mixin-react`

Upcoming related issue and PR in the core repo..

**Comment by toverux** [comment]
I like mixin. It could also become our new terminology to designate that type of API extensions. You're right, _integration_ is not so good because, even if it is some kind of React integration here, other mixins could be totally unrelated to any framework.

**Comment by zenflow** [comment]
> I like mixin. It could also become our new terminology to designate that type of API extensions.

Yes! I'm glad you like it too because it can and will be really useful for that!

**Comment by limonte** [comment]
This component is for the React community, after googling "React mixins" I found a lot of bad words about mixins: 

- harmful, broken https://reactjs.org/blog/2016/07/13/mixins-considered-harmful.html
- dead https://github.com/brigand/react-mixin
- smelly https://www.sitepen.com/blog/2017/08/15/higher-order-components-in-react/

My vote goes against "mixin".

--- 

Since this will be the only one official package for SweetAlert2+React, should we just drop the noun and go with suggested by @toverux in #3 `@sweetalert2/react` or `sweetalert2-react`?

**Comment by zenflow** [comment]
> This component is for the React community, after googling "React mixins" I found a lot of bad words about mixins:

But this isn't a React mixin. It's a SweetAlert2 mixin. We need some word for this kind of extension/decorator pattern used here in the SweetAlert2 ecosystem.  why do we care what people think of **React** "mixins"? 

---

> harmful, broken https://reactjs.org/blog/2016/07/13/mixins-considered-harmful.html

From the article

> **This doesn’t mean that mixins themselves are bad**. People successfully employ them in different languages and paradigms, including some functional languages. At Facebook, we extensively use traits in Hack which are fairly similar to mixins. Nevertheless, we think that mixins are unnecessary and problematic **in React codebases**

--- 

> dead https://github.com/brigand/react-mixin

This is just a legacy package that was superseded by the HOC pattern, the HOC pattern being the more similar to the pattern here.

```js
const {value} = await swal({...promptMixin, title: 'Name?'}) // like a React "mixin"
const {value} = await withReactContent(swal)('Name?') // like a React HOC

`withReactContent` even has a name like `with${featureName}` like conventional HOCs do

```

--- 

> smelly https://www.sitepen.com/blog/2017/08/15/higher-order-components-in-react/

This article (the first one I looked at) is in favor of HOCs.. 

Anyways, the word "smells" appears while describing the project as it was *before* HOCs

> # Enter higher-order components
> The good news is that we can fix all of those problems by using higher-order components

---

@limonte I strongly suggest you use your reasoning (and your brain) instead of randomly inferred sentiments of random people on the web when placing your vote.

**Comment by limonte** [comment]
It's better to be less specific than (potentially) misleading when making names. "Mixin" is misleading, at least for me, because it doesn't fix anyhow my current knowledge about "mixins" (Sass, Polymer, Vue). When I will try to find a way how to use SweetAlert2 with React, the word "mixin" will not come to my mind at all. 

I have the community-driven mindset and I don't think the way you are (scientific), I think from the point of view of a lot of developers who will try to find the appropriate solution for their needs. With "mixin" you would force them to understand wtf is mixin in this context. On the other hand, everybody will understand "integration". Because of the difference of POVs there's a disagreement between us.

It depends on your needs. If you prefer to be scientific, go ahead with "mixin", I am not strongly against it. But, if you want to be more popular - be friendly and as simple as possible to your potential users.

--- 

If I drink too much vodka today, and tomorrow I find a box with the "Acetoxybenzoic acid" label on it, I will not use it, because "acid" will possibly dissolve my stomach.

But label the same box "Aspirin" and I will be very glad to use it right away :)

**Comment by zenflow** [comment]
@limonte "integration" says way too little. It's like a generic filler noun in place of a descriptive noun.. e.g. "Official SweetAlert2 package/thing for React". All it has to be in order to qualify as an integration is use both things (e.g. swal + react, or swal + vue), and we have tons of "integrations" in the ecosystem already. 

There are 2 things I want so that this package can be distinguished: 
  1. states what it is and what it's useful for (reminder: like I said here https://github.com/avil13/vue-sweetalert2/issues/8, being an integration/wrapper for sweetalert2 with a framework does not automatically mean that it is something useful." )
  2. advertises a standard kind of API

the tagline from below in the README (there should only be one tagline btw, not 3)
> sweetalert2-react-content is a sweetalert2 decorator adding support for React elements as content.

Fulfills 1 & 2, and I think the simpler people can still guess that it's an "integration" with React and SweetAlert2, right? Really though, I discourage this kind of thinking where "I'm using Vue, I'm using SweetAlert2, I should search for and install an "integration" that's completely useless or even harmful because I don't understand what I'm doing. This is a reference to this event https://github.com/sweetalert2/sweetalert2/pull/803#issuecomment-356892475 "developers WILL try and find a package for it".

So I generally like the current tagline. 

The term it uses to describe *what* it is (e.g. currently "sweetalert2 decorator") could use more discussion, I'll open an issue in the core repo because this should be aligned in all of the "extensions" (as they're called internally right now).

So if the aim of the PR here is "Add official keyword to README" then we can simply insert "official" before "sweetalert2 decorator". Oh, and package.json description should be updated too. 

If you want to dumb down the tagline you should open an issue for it, but I'm not in favor of it. It's simpler if we give things accurate labels which can be referenced in prescriptions. In your metaphor, I'd ask you to please not take drugs you find, regardless of the name sounding scary (it might be good) or fun (it might be deadly), unless (by the name) you know what they do or have been advised by a doctor.

**Comment by zenflow** [comment]
>  I'll open an issue in the core repo because this should be aligned in all of the "extensions" (as they're called internally right now).

Opened https://github.com/sweetalert2/sweetalert2/issues/1046

**Pull request closed without merging**
